CREATE TABLE "SQL_QUERY" (
 "ID" TEXT,
 "NAME" TEXT NOT NULL UNIQUE,
 "TYPE" TEXT NOT NULL,
 "SQL" TEXT NOT NULL,
 "DESCRIPTION" TEXT,
 "FOREIGN_KEYS_LEGEND" TEXT,
 "TODO" TEXT,
 PRIMARY KEY("ID")
);
