version: "2.4"

services:
  octagon:
    build:
      context: .
      args:
          OCTAGON_MAVEN_REPO_PASSWORD: ${OCTAGON_MAVEN_REPO_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - {path to oct.confpath directory}

