CREATE TABLE "ACTION_LOG" (
 "ID" TEXT,
 "UNIVERSAL_DATE_TIME" TEXT NOT NULL,
 "ACTION_TYPE" TEXT NOT NULL,
 "TYPE" TEXT NOT NULL,
 "OBJECT_ID" TEXT,
 "DATA" TEXT,
 "NAME" TEXT,
 "COMMENT" TEXT,
 "REVISION_NUMBER" INTEGER,
 PRIMARY KEY("ID")
);
