CREATE TABLE "USER"(
 "ID" TEXT,
 "NICK" TEXT NOT NULL UNIQUE,
 "NAME" TEXT NULL,
 "SURNAME" TEXT NULL,
 "E_MAIL" TEXT NOT NULL UNIQUE,
 "ACTIVE" INTEGER NOT NULL DEFAULT TRUE,
 "ROLE_RESTRICTION" TEXT NOT NULL DEFAULT 'READER',
 PRIMARY KEY("ID")
);

CREATE INDEX "INDEX_USER_NICK" ON "USER" ("NICK" ASC);
CREATE INDEX "INDEX_USER_E_MAIL" ON "USER" ("E_MAIL" ASC);
