ALTER TABLE "DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_ACCESS"
        FOREIGN KEY ("ACCESS") REFERENCES "ACCESS" ("ID") ON DELETE No Action ON UPDATE No Action;
ALTER TABLE "DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_SPACE"
        FOREIGN KEY ("SPACE") REFERENCES "SPACE" ("ID") ON DELETE No Action ON UPDATE No Action;
ALTER TABLE "DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_SCHEMA"
        FOREIGN KEY ("SCHEMA") REFERENCES "DOCUMENT" ("ID") ON DELETE No Action ON UPDATE No Action;
ALTER TABLE "DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_REFERENCED_DOCUMENT"
        FOREIGN KEY ("REFERENCED_DOCUMENT") REFERENCES "DOCUMENT" ("ID") ON DELETE No Action ON UPDATE No Action;
