CREATE EXTENSION LTREE;

CREATE TABLE "DOCUMENT"
(
    "ID"          UUID,
    "ACCESS"      UUID  NOT NULL,
    "NAME"        TEXT  NOT NULL,
    "DESCRIPTION" TEXT,
    "GLOBAL_ID"   TEXT UNIQUE,
    "ORDER_NUMBER"   INTEGER,
    "SPACE"       UUID  NOT NULL,
    "PATH"        LTREE NOT NULL,
    "CONTENT"     TEXT,
    "CONTENT_TYPE"     TEXT,
    "JSON"        JSONB,
    "SCHEMA"      UUID,
    "JSON_TYPE"        TEXT DEFAULT 'OFF', -- SCHEMA/VALIDATED_JSON/CHECKED_JSON/FREE_FORM_JSON
    "ADDITIONAL_JSON"        JSONB,
    "TEMPLATE"        BOOLEAN NOT NULL DEFAULT FALSE,
    "CONCEPT"        BOOLEAN NOT NULL DEFAULT FALSE,
    "REFERENCED_DOCUMENT"        UUID
);