CREATE INDEX "IXFK_DOCUMENT_ACCESS" ON "DOCUMENT" ("ACCESS" ASC);
CREATE INDEX "IXFK_DOCUMENT_SPACE" ON "DOCUMENT" ("SPACE" ASC);
CREATE INDEX "IXFK_DOCUMENT_SCHEMA" ON "DOCUMENT" ("SCHEMA" ASC);
CREATE INDEX "IXFK_DOCUMENT_REFERENCED_DOCUMENT" ON "DOCUMENT" ("REFERENCED_DOCUMENT" ASC);