ALTER TABLE "USER_ASSIGNMENT"
    ADD CONSTRAINT "FK_USER_ASSIGNMENT_USER"
        FOREIGN KEY ("USER") REFERENCES "USER" ("ID") ON DELETE No Action ON UPDATE No Action;
ALTER TABLE "USER_ASSIGNMENT"
    ADD CONSTRAINT "FK_USER_ASSIGNMENT_GROUP"
        FOREIGN KEY ("GROUP") REFERENCES "GROUP" ("ID") ON DELETE No Action ON UPDATE No Action;