CREATE TABLE "ACCESS_RIGHT"
(
    "ID"     UUID,
    "READ"   BOOLEAN NOT NULL DEFAULT TRUE,
    "EDIT"   BOOLEAN NOT NULL DEFAULT FALSE,
    "MOVE"   BOOLEAN NOT NULL DEFAULT FALSE,
    "DELETE" BOOLEAN NOT NULL DEFAULT FALSE
);