CREATE INDEX "IXFK_ACCESS_USER" ON "ACCESS" ("USER" ASC);

CREATE INDEX "IXFK_ACCESS_GROUP" ON "ACCESS" ("GROUP" ASC);

CREATE INDEX "IXFK_ACCESS_USER_ACCESS_RIGHT" ON "ACCESS" ("USER_ACCESS_RIGHT" ASC);

CREATE INDEX "IXFK_ACCESS_GROUP_ACCESS_RIGHT" ON "ACCESS" ("GROUP_ACCESS_RIGHT" ASC);

CREATE INDEX "IXFK_ACCESS_OTHER_ACCESS_RIGHT" ON "ACCESS" ("OTHER_ACCESS_RIGHT" ASC);
