ALTER TABLE "ACCESS"
    ADD CONSTRAINT "FK_ACCESS_USER_ACCESS_RIGHT"
        FOREIGN KEY ("USER_ACCESS_RIGHT") REFERENCES "ACCESS_RIGHT" ("ID") ON DELETE No Action ON UPDATE No Action;

ALTER TABLE "ACCESS"
    ADD CONSTRAINT "FK_ACCESS_GROUP_ACCESS_RIGHT"
        FOREIGN KEY ("GROUP_ACCESS_RIGHT") REFERENCES "ACCESS_RIGHT" ("ID") ON DELETE No Action ON UPDATE No Action;

ALTER TABLE "ACCESS"
    ADD CONSTRAINT "FK_ACCESS_OTHER_ACCESS_RIGHT"
        FOREIGN KEY ("OTHER_ACCESS_RIGHT") REFERENCES "ACCESS_RIGHT" ("ID") ON DELETE No Action ON UPDATE No Action;

ALTER TABLE "ACCESS"
    ADD CONSTRAINT "FK_ACCESS_GROUP"
        FOREIGN KEY ("GROUP") REFERENCES "GROUP" ("ID") ON DELETE No Action ON UPDATE No Action;

ALTER TABLE "ACCESS"
    ADD CONSTRAINT "FK_ACCESS_USER"
        FOREIGN KEY ("USER") REFERENCES "USER" ("ID") ON DELETE No Action ON UPDATE No Action;