ALTER TABLE "SPACE"
    ADD CONSTRAINT "FK_SPACE_ACCESS"
        FOREIGN KEY ("ACCESS") REFERENCES "ACCESS" ("ID") ON DELETE No Action ON UPDATE No Action;
ALTER TABLE "SPACE"
    ADD CONSTRAINT "FK_SPACE_DATABASE"
        FOREIGN KEY ("DATABASE") REFERENCES "DATABASE" ("ID") ON DELETE No Action ON UPDATE No Action;