CREATE TABLE "WEBSITE" (
	"NUMBER"	INTEGER,
	"URL"	TEXT NOT NULL CHECK("URL" NOT LIKE '%/') UNIQUE,
	"WEB_ARCHIVE_SNAPSHOT"	TEXT,
	"LANGUAGE"	TEXT,
	"DOWNLOADED"	INTEGER,
	"FORMATTED"	INTEGER,
	"VERIFIED"	INTEGER DEFAULT 0,
	"VARIANT_NUMBER"	INTEGER,
	"ARCHIVES"	TEXT,
	"COMMENT"	TEXT,
	CONSTRAINT "FK_VARIANT_WEBPAGE" FOREIGN KEY("VARIANT_NUMBER") REFERENCES "VARIANT",
	PRIMARY KEY("NUMBER" AUTOINCREMENT)
);