CREATE TABLE "VARIANT" (
	"NUMBER"	INTEGER,
	"NAME"	TEXT,
	"NOTE"	TEXT,
	"STATUS"	TEXT,
	"AUTHOR"	TEXT,
	"LICENCE"	TEXT,
	"OPEN_SOURCE"	INTEGER,
	"USER_INTERFACE"	TEXT,
	"PROGRAMMING_LANGUAGE"	TEXT,
	"BINARIES"	INTEGER,
	"LAST_UPDATE"	TEXT,
	"LAST_VERSION"	TEXT,
	PRIMARY KEY("NUMBER" AUTOINCREMENT)
);