CREATE TABLE "WHINING" (
 "ID" TEXT,
 "EMAIL_SUBJECT" TEXT NOT NULL,
 "EMAIL_DESCRIPTIVE_TEXT" TEXT NOT NULL,
 "SEND_EVEN_IF_NOTHING_FOUND" INTEGER,
 "ENABLED" INTEGER,
 "RUN_EVERY_X_DAYS" INTEGER,
 "CRON_EXPRESSION" TEXT,
 "LAST_RUN" TEXT,
 "LAST_FAILURE" TEXT,
 "LAST_FAILURE_MSG" TEXT,
 PRIMARY KEY("ID")
);
