CREATE TABLE "WHINING_ASSIGNMENT" (
 "ID" TEXT,
 "TITLE" TEXT NOT NULL,
 "WHINING_ID" TEXT NOT NULL,
 "QUERY_ID" TEXT,
 "SQL_QUERY_ID" TEXT,
 "SORTKEY" INTEGER,
 FOREIGN KEY("SQL_QUERY_ID") REFERENCES "SQL_QUERY"("ID"),
 FOREIGN KEY("WHINING_ID") REFERENCES "WHINING"("ID"),
 PRIMARY KEY("ID"),
 FOREIGN KEY("QUERY_ID") REFERENCES "QUERY"("ID")
);
